export const FETCH_PRODUCT_CATEGORY_DETAIL = 'FETCH_PRODUCT_CATEGORY_DETAIL';
export const FETCH_PRODUCT_CATEGORY_DETAIL_SUCCESS =
  'FETCH_PRODUCT_CATEGORY_DETAIL_SUCCESS';
export const FETCH_PRODUCT_CATEGORY_DETAIL_FAILED =
  'FETCH_PRODUCT_CATEGORY_DETAIL_FAILED';

export const FETCH_PRODUCT_CATEGORY = 'FETCH_PRODUCT_CATEGORY';
export const FETCH_PRODUCT_CATEGORY_SUCCESS = 'FETCH_PRODUCT_CATEGORY_SUCCESS';
export const FETCH_PRODUCT_CATEGORY_FAILED = 'FETCH_PRODUCT_CATEGORY_FAILED';

export const FILTER_PRODUCT_CATEGORY = 'FILTER_PRODUCT_CATEGORY';
export const FILTER_PRODUCT_CATEGORY_SUCCESS =
  'FILTER_PRODUCT_CATEGORY_SUCCESS';

export const ADD_PRODUCT_CATEGORY = 'ADD_PRODUCT_CATEGORY';
export const ADD_PRODUCT_CATEGORY_SUCCESS = 'ADD_PRODUCT_CATEGORY_SUCCESS';
export const ADD_PRODUCT_CATEGORY_FAILED = 'ADD_PRODUCT_CATEGORY_FAILED';

export const SET_PRODUCT_CATEGORY_UPDATING = 'SET_PRODUCT_CATEGORY_UPDATING';

export const UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY';
export const UPDATE_PRODUCT_CATEGORY_SUCCESS =
  'UPDATE_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_PRODUCT_CATEGORY_FAILED = 'UPDATE_PRODUCT_CATEGORY_FAILED';

export const DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY';
export const DELETE_PRODUCT_CATEGORY_SUCCESS =
  'DELETE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_PRODUCT_CATEGORY_FAILED = 'DELETE_PRODUCT_CATEGORY_FAILED';
