export const FETCH_XPRODUCT_PRODUCT_CATEGORY_DETAIL =
  'FETCH_XPRODUCT_PRODUCT_CATEGORY_DETAIL';
export const FETCH_XPRODUCT_PRODUCT_CATEGORY_DETAIL_SUCCESS =
  'FETCH_XPRODUCT_PRODUCT_CATEGORY_DETAIL_SUCCESS';
export const FETCH_XPRODUCT_PRODUCT_CATEGORY_DETAIL_FAILED =
  'FETCH_XPRODUCT_PRODUCT_CATEGORY_DETAIL_FAILED';

export const FETCH_XPRODUCT_PRODUCT_CATEGORY =
  'FETCH_XPRODUCT_PRODUCT_CATEGORY';
export const FETCH_XPRODUCT_PRODUCT_CATEGORY_SUCCESS =
  'FETCH_XPRODUCT_PRODUCT_CATEGORY_SUCCESS';
export const FETCH_XPRODUCT_PRODUCT_CATEGORY_FAILED =
  'FETCH_XPRODUCT_PRODUCT_CATEGORY_FAILED';

export const FILTER_XPRODUCT_PRODUCT_CATEGORY =
  'FILTER_XPRODUCT_PRODUCT_CATEGORY';
export const FILTER_XPRODUCT_PRODUCT_CATEGORY_SUCCESS =
  'FILTER_XPRODUCT_PRODUCT_CATEGORY_SUCCESS';

export const FILTER_XPRODUCT_PRODUCT_CATEGORY_FAILED =
  'FILTER_XPRODUCT_PRODUCT_CATEGORY_FAILED';

export const ADD_XPRODUCT_PRODUCT_CATEGORY = 'ADD_XPRODUCT_PRODUCT_CATEGORY';
export const ADD_XPRODUCT_PRODUCT_CATEGORY_SUCCESS =
  'ADD_XPRODUCT_PRODUCT_CATEGORY_SUCCESS';
export const ADD_XPRODUCT_PRODUCT_CATEGORY_FAILED =
  'ADD_XPRODUCT_PRODUCT_CATEGORY_FAILED';

export const SET_XPRODUCT_PRODUCT_CATEGORY_UPDATING =
  'SET_XPRODUCT_PRODUCT_CATEGORY_UPDATING';

export const UPDATE_XPRODUCT_PRODUCT_CATEGORY =
  'UPDATE_XPRODUCT_PRODUCT_CATEGORY';
export const UPDATE_XPRODUCT_PRODUCT_CATEGORY_SUCCESS =
  'UPDATE_XPRODUCT_PRODUCT_CATEGORY_SUCCESS';
export const UPDATE_XPRODUCT_PRODUCT_CATEGORY_FAILED =
  'UPDATE_XPRODUCT_PRODUCT_CATEGORY_FAILED';

export const DELETE_XPRODUCT_PRODUCT_CATEGORY =
  'DELETE_XPRODUCT_PRODUCT_CATEGORY';
export const DELETE_XPRODUCT_PRODUCT_CATEGORY_SUCCESS =
  'DELETE_XPRODUCT_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_XPRODUCT_PRODUCT_CATEGORY_FAILED =
  'DELETE_XPRODUCT_PRODUCT_CATEGORY_FAILED';
